# See http://readme.drone.io/usage/overview
pipeline:
  build:
    image: docker.kbt.io/librttopo/build-test:debian-sid
    commands:
      - ./autogen.sh
      - ./configure CFLAGS="-Wall"
      - make
      - make distcheck
